version: "3.8"
services:
  datamart:
    build: ./data-mart
    image: datamart:latest
    volumes:
      - ./data-mart/data:/data
    environment:
      - INPUT_PATH=${INPUT_PATH}
      - OUTPUT_PATH=${OUTPUT_PATH}
      - SPARK_MASTER=${SPARK_MASTER}
      - DB_URL=${DB_URL}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    command: [
      "/opt/bitnami/spark/bin/spark-submit",
      "--class", "com.example.datamart.DataMartApp",
      "--master", "local[*]",
      "/opt/app/datamart.jar",
      "--inputPath", "${INPUT_PATH}",
      "--outputPath", "${OUTPUT_PATH}"
    ]