version: "3.8"
services:
  datamart:
    build: ./data-mart
    image: datamart:latest
    volumes:
      - ./data-mart/data:/data
    environment:
      - INPUT_PATH=/data/en.openfoodfacts.org.products.csv.gz
      - OUTPUT_PATH=/data/output_parquet
      - SPARK_MASTER=local[*]
    command: [
      "/opt/bitnami/spark/bin/spark-submit",
      "--class", "com.example.datamart.DataMartApp",
      "--master", "local[*]",
      "/opt/app/datamart.jar",
      "--inputPath", "${INPUT_PATH}",
      "--outputPath", "${OUTPUT_PATH}"
    ]