app_name: ModelTraining
config:
  spark.driver.memory: 4g
  spark.executor.memory: 4g
  spark.executor.cores: 2
  spark.sql.shuffle.partitions: 100
  spark.sql.execution.arrow.pyspark.enabled: true
  spark.dynamicAllocation.enabled: false
  spark.ui.showConsoleProgress: true

  spark.eventLog.enabled: true
  spark.eventLog.dir: /app/outputs/spark-events